name: Gov Contract CI - Deploy

on:
  pull_request:
  push:
    tags:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose
        run: STAKE_TOKEN="ujunox" docker-compose up -d
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'CosmosContracts/cw-unity-prop'
          ref: 'v0.3.2'
      - name: Test gov deploy
        run: |
          chmod a+x ./scripts/deploy_ci.sh
          ./scripts/deploy_ci.sh juno16g2rahf5846rxzp3fwlswy08fz8ccuwk03k57y

